# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Python Data Science Handbook
site_url: https://github.com/jakevdp/PythonDataScienceHandbook
site_author: Jake VanderPlas

site_description:

# Repository
repo_name: jakevdp/PythonDataScienceHandbook
repo_url: https://github.com/jakevdp/PythonDataScienceHandbook
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: en
  logo: images/logo.bmp
  favicon: images/logo_python.svg
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jakevdp
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jake-vanderplas-5894937b/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jakevdp
    - icon: fontawesome/solid/globe
      link: http://vanderplas.com/



# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - Home: index.md
    - notebooks/00.00-Preface.ipynb
    - IPython - Beyond Normal Python:
        - notebooks/01.00-IPython-Beyond-Normal-Python.ipynb
        - notebooks/01.01-Help-And-Documentation.ipynb
        - notebooks/01.02-Shell-Keyboard-Shortcuts.ipynb
        - notebooks/01.03-Magic-Commands.ipynb
        - notebooks/01.04-Input-Output-History.ipynb
        - notebooks/01.05-IPython-And-Shell-Commands.ipynb
        - notebooks/01.06-Errors-and-Debugging.ipynb
        - notebooks/01.07-Timing-and-Profiling.ipynb
        - notebooks/01.08-More-IPython-Resources.ipynb
    - Introduction to NumPy:
        - notebooks/02.00-Introduction-to-NumPy.ipynb
        - notebooks/02.01-Understanding-Data-Types.ipynb
        - notebooks/02.02-The-Basics-Of-NumPy-Arrays.ipynb
        - notebooks/02.03-Computation-on-arrays-ufuncs.ipynb
        - notebooks/02.04-Computation-on-arrays-aggregates.ipynb
        - notebooks/02.05-Computation-on-arrays-broadcasting.ipynb
        - notebooks/02.06-Boolean-Arrays-and-Masks.ipynb
        - notebooks/02.07-Fancy-Indexing.ipynb
        - notebooks/02.08-Sorting.ipynb
        - notebooks/02.09-Structured-Data-NumPy.ipynb
    - Data Manipulation with Pandas:
        - notebooks/03.00-Introduction-to-Pandas.ipynb
        - notebooks/03.01-Introducing-Pandas-Objects.ipynb
        - notebooks/03.02-Data-Indexing-and-Selection.ipynb
        - notebooks/03.03-Operations-in-Pandas.ipynb
        - notebooks/03.04-Missing-Values.ipynb
        - notebooks/03.05-Hierarchical-Indexing.ipynb
        - notebooks/03.06-Concat-And-Append.ipynb
        - notebooks/03.07-Merge-and-Join.ipynb
        - notebooks/03.08-Aggregation-and-Grouping.ipynb
        - notebooks/03.09-Pivot-Tables.ipynb
        - notebooks/03.10-Working-With-Strings.ipynb
        - notebooks/03.11-Working-with-Time-Series.ipynb
        - notebooks/03.12-Performance-Eval-and-Query.ipynb
        - notebooks/03.13-Further-Resources.ipynb
    - Visualization with Matplotlib:
        - notebooks/04.00-Introduction-To-Matplotlib.ipynb
        - notebooks/04.01-Simple-Line-Plots.ipynb
        - notebooks/04.02-Simple-Scatter-Plots.ipynb
        - notebooks/04.03-Errorbars.ipynb
        - notebooks/04.04-Density-and-Contour-Plots.ipynb
        - notebooks/04.05-Histograms-and-Binnings.ipynb
        - notebooks/04.06-Customizing-Legends.ipynb
        - notebooks/04.07-Customizing-Colorbars.ipynb
        - notebooks/04.08-Multiple-Subplots.ipynb
        - notebooks/04.09-Text-and-Annotation.ipynb
        - notebooks/04.10-Customizing-Ticks.ipynb
        - notebooks/04.11-Settings-and-Stylesheets.ipynb
        - notebooks/04.12-Three-Dimensional-Plotting.ipynb
        - notebooks/04.13-Geographic-Data-With-Basemap.ipynb
        - notebooks/04.14-Visualization-With-Seaborn.ipynb
        - notebooks/04.15-Further-Resources.ipynb
    - Machine Learning:
        - notebooks/05.00-Machine-Learning.ipynb
        - notebooks/05.01-What-Is-Machine-Learning.ipynb
        - notebooks/05.02-Introducing-Scikit-Learn.ipynb
        - notebooks/05.03-Hyperparameters-and-Model-Validation.ipynb
        - notebooks/05.04-Feature-Engineering.ipynb
        - notebooks/05.05-Naive-Bayes.ipynb
        - notebooks/05.06-Linear-Regression.ipynb
        - notebooks/05.07-Support-Vector-Machines.ipynb
        - notebooks/05.08-Random-Forests.ipynb
        - notebooks/05.09-Principal-Component-Analysis.ipynb
        - notebooks/05.10-Manifold-Learning.ipynb
        - notebooks/05.11-K-Means.ipynb
        - notebooks/05.12-Gaussian-Mixtures.ipynb
        - notebooks/05.13-Kernel-Density-Estimation.ipynb
        - notebooks/05.14-Image-Features.ipynb
        - notebooks/05.15-Learning-More.ipynb
